mybatis-plus:
  type-aliases-package: ysu.lgq.sale_erp.pojo
  mapper-locations: classpath:/mapper/*.xml
  configuration:
    # 下划线和驼啊峰命名转换
    map-underscore-to-camel-case: true
    # 启用SQL日志（开发环境建议）
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
