# ===============================
# = 应用服务配置
# ===============================
# 应用服务 WEB 访问端口
server:
  port: 9000
  servlet:
    encoding:
      charset: UTF-8

---
# ===============================
# = 日志配置
# ===============================
# 设置日志级别
logging:
  level:
    root: INFO
    org.springframework: INFO

---
# ===============================
# = 数据库配置
# ===============================
# MySQL 数据源配置
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/sale_erp?useSSL=false&serverTimezone=UTC
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver

---
# ===============================
# = MyBatis-Plus 配置
# ===============================
# MyBatis-Plus 实体类包路径
mybatis-plus:
  type-aliases-package: ysu.lgq.sale_erp.pojo
  mapper-locations: classpath:/mapper/*.xml
  configuration:
    map-underscore-to-camel-case: true
    # 新增：启用SQL日志（开发环境建议）
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

---
# ===============================
# = Redis 配置
# ===============================
# Redis数据库索引（默认为0）
spring:
  data:
    redis:
      database: 0
      host: 127.0.0.1
      port: 6379
      password:
      timeout: 3000
      lettuce:
        pool:
          max-active: 8
          # 连接池最大阻塞等待时间（使用负值表示没有限制） 默认 -1
          max-wait: -1
          # 连接池中的最大空闲连接 默认 8
          max-idle: 8
          # 连接池中的最小空闲连接 默认 0
          min-idle: 0

---
# ===============================
# = 安全与调试配置
# ===============================
# 生产环境需禁用热部署
spring:
  devtools:
    restart:
      enabled: true

  # 新增：JWT 配置（根据实际需求）
  # jwt:
  #   secret: your-secret-key
  #   expiration: 86400  # 24小时

  # 新增：文件上传限制（可选）
  # servlet:
  #   multipart:
  #     max-file-size: 10MB
  #     max-request-size: 10MB

  # 新增：跨域配置（前端联调时启用）
  # mvc:
  #   cors:
  #     allowed-origins: http://localhost:8080
  #     allowed-methods: GET,POST,PUT,DELETE